language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

before_script:
    - composer self-update
    - composer install

script:
    - vendor/bin/phpunit --coverage-clover coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

branches:
    only:
        - master
